INSERT INTO `program` (`prog_id`,`name`,`department`)
VALUES
  (200,"NSF-NIST Interaction in Basic and Applied Scientific Research","Department of Natural Sciences"),
  (201,"MPS-Ascend External Mentoring","Department of Natural Sciences"),
  (202,"Cyberinfrastructure for Sustained Scientific Innovation","Department of Natural Sciences"),
  (203,"Broadening Participation in Computing (BPC)","Department of Engineering & Technology"),
  (204,"CISE Community Research Infrastructure (CCRI)","Department of Engineering & Technology"),
  (205,"Computer and Network Systems : Core Programs","Department of Engineering & Technology"),
  (206,"Collaborative Research in Computational Neuroscience (CRCNS)","Department of Life Sciences"),
  (207,"Panel Study of Income Dynamics Competition","Department of Life Sciences"),
  (208,"Incorporating Human Behavior in Epidemiological Models (IHBEM)","Department of Life Sciences"),
  (209,"Plant Biotic Interactions","Department of Agricultural Sciences"),
  (210,"Developing Country Collaborations in Plant Genome Research","Department of Agricultural Sciences"),
  (211,"Signals in the Soil","Department of Agricultural Sciences"),
  (212,"Social Psychology","Department of Social Sciences"),
  (213,"General Social Survey Competition","Department of Social Sciences"),
  (214,"Smart and Connected Communities (S&CC)","Department of Social Sciences"),
  (215,"Behavioral Systems","Department of Humanities and Arts"),
  (216,"Law & Science (LS)","Department of Humanities and Arts"),
  (217,"Cultural Anthropology Research Experience for Graduates (REG)","Department of Humanities and Arts"),
  (218,"Humans, Disasters, and the Built Environment (HDBE)","Department of Environment & Energy"),
  (219,"Human-Environment and Geographical Sciences Program (HEGS)","Department of Environment & Energy"),
  (220,"NSF/NSFC Joint Research on Environmental Sustainability Challenges","Department of Environment & Energy"),
  (221,"Developing Long-term Strategies to Transform Manufacturing","Department of Management and Economics of Innovation"),
  (222,"Opportunities for Collaboration between CISE and SBE Researchers","Department of Management and Economics of Innovation"),
  (223,"SBE Perspectives on Graduate Education","Department of Management and Economics of Innovation"),
  (224,"Decision, Risk and Management Sciences (DRMS)","Department of Management and Economics of Innovation"),
  (225,"NSF-NIST Interaction in Basic and Applied Scientific Research","Department of Engineering & Technology"),
  (226,"Connections in Quantum Information Science (CQIS)","Department of Natural Sciences"),
  (227,"Mid-scale Research Infrastructure - Engineering Conferences","Department of Engineering & Technology"),
  (228,"Secure Analog-RF Electronics and Electromagnetics (SARE)","Department of Engineering & Technology"),
  (229,"Partnership for Prototyping of CMOS+X Systems","Department of Engineering & Technology");