INSERT INTO `science` (`sc_id`,`name`)
VALUES
  (1,"Mathematics"),
  (2,"Computer and information science"),
  (3,"Physical science"),
  (4,"Chemical science"),
  (5,"Biological science"),
  (6,"Earth and related Environmental sciences"),
  (7,"Civil engineering"),
  (8,"Chemical engineering"),
  (9,"Mechanical engineering"),
  (10,"Medical engineering"),
  (11,"Electrical engineering,Electronic engineering"),
  (12,"Environmental engineering"),
  (13,"Environmental biotechnology"),
  (14,"Industrial biotechnology"),
  (15,"Nano-technology"),
  (16,"Basic medicine"),
  (17,"Clinical medicine"),
  (18,"Health Science"),
  (19,"Medical biotechnology"),
  (20,"Agriculture, Forestry, and Fisheries"),
  (21,"Animal and Dairy science"),
  (22,"Veterinary science"),
  (23,"Agricultural biotechnology"),
  (24,"Psychology"),
  (25,"Economies and Business"),
  (26,"Educational sciences"),
  (27,"Sociology"),
  (28,"Law"),
  (29,"Political science"),
  (30,"Social and economic geography"),
  (31,"Media and communications"),
  (32,"History and Archaeology"),
  (33,"Languages and Literature"),
  (34,"Philosophy, Ethics and Religion"),
  (35,"Political science"),
  (36,"Arts(arts,history of arts,music)");  